# Generated by Django 3.2.11 on 2022-01-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220109_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
